export const DATA_SOURCE_OPTIONS = [
  { id: 'live', label: 'Live Xert' },
  { id: 'recovery', label: 'Mock: Recovery' },
  { id: 'low-deficit', label: 'Mock: Low Deficit' },
  { id: 'mixed-deficit', label: 'Mock: Mixed Deficits' },
  { id: 'peak-focus', label: 'Mock: Peak Focus' },
];

export const MOCK_SCENARIOS = {
  recovery: {
    title: 'Recovery',
    trainingData: {
      status: 'Tired',
      weight: 78.4,
      signature: {
        ftp: 238,
        ltp: 178,
        hie: 18.7,
        pp: 1054,
      },
      tl: { low: 42.1, high: 8.4, peak: 3.2, total: 53.7 },
      targetXSS: { low: 26, high: 0, peak: 0, total: 26 },
      wotd: {
        name: null,
        difficulty: null,
        description: null,
      },
    },
    rawWotd: { type: 'None' },
    dailySummary: {
      count: 1,
      completed: { low: 31, high: 0, peak: 0, total: 31 },
      targets: { low: 26, high: 0, peak: 0, total: 26 },
      remaining: { low: 0, high: 0, peak: 0, total: 0 },
    },
  },
  'low-deficit': {
    title: 'Low Deficit',
    trainingData: {
      status: 'Fresh',
      weight: 76.8,
      signature: {
        ftp: 252,
        ltp: 184,
        hie: 20.9,
        pp: 1120,
      },
      tl: { low: 18.5, high: 4.2, peak: 2.1, total: 24.8 },
      targetXSS: { low: 42, high: 10, peak: 4, total: 56 },
      wotd: {
        name: 'Steady Foundations',
        difficulty: 'Moderate',
        description: 'Aerobic endurance focus with long controlled efforts.',
      },
    },
    rawWotd: {
      name: 'Steady Foundations',
      difficulty: 'Moderate',
      description: 'Aerobic endurance focus with long controlled efforts.',
      xss: 58,
      lowXSS: 46,
      highXSS: 10,
      peakXSS: 2,
      duration: 4200,
    },
    dailySummary: {
      count: 0,
      completed: { low: 8, high: 1, peak: 0, total: 9 },
      targets: { low: 42, high: 10, peak: 4, total: 56 },
      remaining: { low: 34, high: 9, peak: 4, total: 47 },
    },
  },
  'mixed-deficit': {
    title: 'Mixed Deficits',
    trainingData: {
      status: 'Fresh',
      weight: 72.3,
      signature: {
        ftp: 266,
        ltp: 191,
        hie: 22.4,
        pp: 1168,
      },
      tl: { low: 20.1, high: 10.8, peak: 4.7, total: 35.6 },
      targetXSS: { low: 32, high: 28, peak: 12, total: 72 },
      wotd: {
        name: 'Rolling Pressure',
        difficulty: 'Hard',
        description: 'Repeated threshold surges with recoveries between efforts.',
      },
    },
    rawWotd: {
      name: 'Rolling Pressure',
      difficulty: 'Hard',
      description: 'Repeated threshold surges with recoveries between efforts.',
      xss: 72,
      lowXSS: 22,
      highXSS: 38,
      peakXSS: 12,
      duration: 3300,
    },
    dailySummary: {
      count: 1,
      completed: { low: 12, high: 8, peak: 3, total: 23 },
      targets: { low: 32, high: 28, peak: 12, total: 72 },
      remaining: { low: 20, high: 20, peak: 9, total: 49 },
    },
  },
  'peak-focus': {
    title: 'Peak Focus',
    trainingData: {
      status: 'Fresh',
      weight: 69.1,
      signature: {
        ftp: 281,
        ltp: 201,
        hie: 24.3,
        pp: 1246,
      },
      tl: { low: 12.5, high: 7.3, peak: 1.6, total: 21.4 },
      targetXSS: { low: 20, high: 14, peak: 18, total: 52 },
      wotd: {
        name: 'Snap and Recover',
        difficulty: 'Hard',
        description: 'Short maximal efforts with full recoveries.',
      },
    },
    rawWotd: {
      name: 'Snap and Recover',
      difficulty: 'Hard',
      description: 'Short maximal efforts with full recoveries.',
      xss: 54,
      lowXSS: 10,
      highXSS: 10,
      peakXSS: 34,
      duration: 2400,
    },
    dailySummary: {
      count: 0,
      completed: { low: 5, high: 3, peak: 0, total: 8 },
      targets: { low: 20, high: 14, peak: 18, total: 52 },
      remaining: { low: 15, high: 11, peak: 18, total: 44 },
    },
  },
};
