// routes.js — re-exports bundled route data and world name map.
// routes-data.js is generated by: node bundle-routes.mjs

export { routes } from './routes-data.js';

export const WORLD_NAMES = {
  watopia:         'Watopia',
  london:          'London',
  'new-york':      'New York',
  innsbruck:       'Innsbruck',
  richmond:        'Richmond',
  bologna:         'Bologna',
  yorkshire:       'Yorkshire',
  'crit-city':     'Crit City',
  'makuri-islands':'Makuri Islands',
  france:          'France',
  paris:           'Paris',
  scotland:        'Scotland',
};

export function worldName(slug) {
  return WORLD_NAMES[slug] ?? slug;
}
